import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Explicit sidebar, not autogenerated: seven pages is small and curated enough
 * that filesystem order would be one accident away from a wrong reading order
 * (getting-started before run-the-backend, first-review before findings-and-fix).
 */
const sidebars: SidebarsConfig = {
  docs: [
    {
      type: "category",
      label: "Start here",
      collapsed: false,
      items: ["start-here/getting-started", "start-here/run-the-backend"],
    },
    {
      type: "category",
      label: "Reviewing",
      collapsed: false,
      items: [
        "reviewing/providers",
        "reviewing/first-review",
        "reviewing/findings-and-fix",
      ],
    },
    {
      type: "category",
      label: "Advanced",
      items: ["advanced/cli-and-ci", "advanced/privacy-and-data"],
    },
  ],
};

export default sidebars;
